### ISSUE TITLE
Option to not include "src" attribute

### ISSUE THREAD

**Issue by lucalanca** [smaxtastic/grunt-responsive-images-extender#2]
So the original image doesn't get downloaded before the picturefill starts doing it's thing.
In a project I'm working on, the original image is also the biggest one, thus the issue. Or am I doing something wrongly?

**Comment by jegtnes** [comment]
Hey @smaxtastic! Just butting in here. Thanks for this great task.

If you've got an image with both a src and a srcset and srcset isn't natively supported (but instead polyfilled by something like Picturefill), you'll encounter a double download. This can be avoided by omitting the src attribute entirely, or add a blank spacer gif as the source instead (hello 1999!): `<img src="data:image/gif;base64,R0lGODlhAQABAAAAADs=" srcset="stuffs" alt="">`.

So what @lucalanca is asking for is:

Transforming `<img src="goat.jpg" alt="A handsome goat">` to `<img srcset="goat-small.jpg 300w, goat-large.jpg 600w" alt="A handsome goat">`

I'll see if I can find some time to create a PR for this at some point soon as I'd like to see this behaviour myself :)

**Comment by lucalanca** [comment]
This got lost on my notifications. What @jegtnes said it's exactly what I should have written in this issue.

**Comment by smaxtastic** [comment]
I see, thanks for clarifying @jegtnes! It would be awesome if you could file a PR for this, since I am quite busy right now. Looking forward to it!

**Comment by smaxtastic** [comment]
Happy days guys, I am in the course of giving this task a major update and read available sizes directly from the image files. I will also include an option to leave the `src` attribute untouched, put the smalles available image in there or get rid of it entirely. I hope this will help.

**Comment by smaxtastic** [comment]
It is now possible to remove the `src` attribute by setting the option `srcAttribute` to `'none'.`
