### ISSUE TITLE
Using srcsetRetina option only

### ISSUE THREAD

**Issue by tigranpetrossian** [smaxtastic/grunt-responsive-images-extender#3]
Is it possible to use the plugin for just generating srcsets with @2x versions? I can't make neither "non-responsive.png" example from docs, nor the code below to work. It generates default size srcsets, as if the options were empty:

**Edit:** Figured out that in order to make Retina work, `width` attribute should be specified. Any workaround to make it work without an attribute?

    responsive_images_extender: {
      complete: {
        options: {
          srcsetRetina: [{
            suffix: '@2x',
            value: '2x'
          }]
        },
        files: [{
          expand: true,
          src: ['index.html'],
          cwd: '',
          dest: 'build/'
        }]
      }
    }

**Comment by smaxtastic** [comment]
Hi @tigranpetrossian,

As far as I understand, the srcsetRetina option only makes sense for images with a set width. Because once you have images without an explicit width you can make the browser account for different pixel densities with srcset+sizes. Please read [this article](https://jakearchibald.com/2015/anatomy-of-responsive-images/) for more information, where Jake states:

> You don't need to specify density, the browser figure that out itself.

Does that make sense to you?

**Comment by tigranpetrossian** [comment]
Hi @smaxtastic 

Thanks for getting back to this. I'm familiar with the spec. At the time of opening this issue a few important browsers supported only the resolution switching part of the syntax (1x, 2x, etc) - http://caniuse.com/#search=srcset

The issue is N/A for me since I moved to gulp. Just wanted to clarify.

**Comment by smaxtastic** [comment]
@tigranpetrossian Gotcha, thanks for closing. How is it working on gulp? Is there a plugin for automatically set sizes and srcset. I am about to give my plugin a major update, reading available sizes directly from the image files and was wondering if it would be worthwhile to do the same thing for gulp.
