### ISSUE TITLE
Removes self closing forward slashes from inline SVG path elements

### ISSUE THREAD

**Issue by davidensinger** [smaxtastic/grunt-responsive-images-extender#4]
Hi,

This plugin works like a dream, except that it strips self closing forward slashes from inline SVG path elements in inline SVGs:

 ```
<path d="..."/>
```
becomes
 ```
<path d="...">
```

And that breaks the inline SVGs that I have on my site (that have more than one path), unfortunately. I tried ignoring the `<svg>` and `<path>` elements via the ignore option, but to no avail. I also tried explicitly closing the paths:

 ```
<path d="..."></path>
```

But those got mangled too.

Any idea what’s happening? Here’s [a link](https://github.com/davidensinger/davidensinger.github.io/blob/source/Gruntfile.js#L259-L378) to how I’ve configured the plugin in my Gruntfile, if that’s any help. I’ve commented out the task itself for the time being.

**Comment by smaxtastic** [comment]
Very strange... Sorry I am getting back to you so late, but I will look into this.

**Comment by smaxtastic** [comment]
Okay, so this is due to the HTML parser that is behind Cheerio, the library I use for traversing the DOM. But I saw that there is a PR from 3 days ago to get this fixed. I'm on it. Thanks for pointing this out!

**Comment by davidensinger** [comment]
Great! Thank you for looking into this :)

**Comment by smaxtastic** [comment]
This is now solved. The current version of cheerio is treating SVG code as XML and recognizes self-closing tags.
