### ISSUE TITLE
Add ability to apply srcset conditionally based on selector

### ISSUE THREAD

**Issue by johnv-git** [smaxtastic/grunt-responsive-images-extender#5]
Currently a srcset is applied to every image tag (except those with a pre-existing srcset). This might affect image tags you'd prefer to leave alone.  I've added an optional options.selector which, if defined, will only apply to matching tags.

```
--- responsive_images_extender.js.orig  2015-10-05 15:04:15.250587100 -0700
+++ responsive_images_extender.js       2015-10-07 15:06:42.355054900 -0700
@@ -93,7 +93,7 @@
           grunt.log.verbose.ok('Detected width attribute for ' + filePath + fileExt + ' (not responsive, but retina-ready)');
         }
         else {
-          if (!hasSrcset) {
+          if (!hasSrcset && (options.selector === undefined || image.is(options.selector))) {
             image.attr('srcset', buildAttributeList(options.srcset, buildSrc));
             grunt.log.verbose.ok('Extend ' + filePath + fileExt + ' with srcset attribute');
           }
```

**Comment by smaxtastic** [comment]
Hi @johnv-git,

Thank you for your contribution. I am just wondering if `options.ignore` is not what you are looking for.. All the selectors in the `ignore` array are not touched by the algorithm.

Regards,
Stephan

**Comment by johnv-git** [comment]
`options.ignore` was close, but for this particular one-off workflow I had preexisting img tags I wanted to leave alone while processing new img tags that I was adding.  (Basically giving me a before/after for static images vs responsive.)  It was easier to add the new tags with a specific class than it was to touch all of the existing tags.

The other thing that you could do with an inclusive `options.selector` is to process different img tags to have different srcsets.  Just set up multiple tasks with the same files specification, but a different selector and different srcset.  I don't need to do that, but perhaps someone somewhere is sad about the lack.

Thanks for the plugin btw, I'm having great fun with it and grunt-responsive-images.

**Comment by smaxtastic** [comment]
Alright, I hear you. Yes that makes sense.

I am in the course of giving this plugin a major update to make configuration easier. Basically, I am aiming at deriving the `srcset` for every image by scanning the files directly. That should solve your problem, right? If you have only `image.png` then no `srcset` will be added. However, if the plugin finds `image.png`, `image-320.png`, `image-800.png`… it will create the `srcset` accordingly and add it to the tag unless the tag is part of the ignore list.

**Comment by smaxtastic** [comment]
The updated version behaves as explained above. This should solve your problem.
