### ISSUE TITLE
Stop special characters (umlauts) from being converted into hexadecimal values within the whole file

### ISSUE THREAD

**Issue by treiber** [smaxtastic/grunt-responsive-images-extender#6]
I came across an issue with special characters whenever I parse my php file.
Letters such as:
```
Ä Ö Ü & % §
```
gets compiled into
```html
&#xC4; &#xD6; &#xDC; &amp; % &#xA7;
```
respectively. That's within the whole document, not just the images' alt attribute. Is there any way to stop this behavior?
```html
<meta charset="utf-8">
```
is set in the document head.

**Comment by smaxtastic** [comment]
Hi Nik,
Thanks for pointing this out. I will look into it and have it fixed with the next update coming this weekend.
Cheers,
Stephan

**Comment by smaxtastic** [comment]
This is fixed now.
